"""
Django settings for django_openapi_proxy project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
import secrets
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from decouple import Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_PATH = os.path.join(BASE_DIR, '.env')

PROVIDERS_PATH = os.path.join(BASE_DIR, 'providers.json')
EXAMPLE_PATH = os.path.join(BASE_DIR, 'providers.example.json')

# Contenido del ejemplo (con claves falsas y comentarios explicativos)
DEFAULT_PROVIDERS_CONTENT = [
    {
        "name": "Groq",
        "URL_API":"https://console.groq.com/keys",
        "URL_models":"https://console.groq.com/docs/models",
        "url": "https://api.groq.com/openai/v1/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "_top":"openai/gpt-oss-120b",
            "_low":"openai/gpt-oss-20b",
            "Llama 3.1 8B":"llama-3.1-8b-instant",
            "Llama 3.3 70B":"llama-3.3-70b-versatile",
            "Llama Guard 4 12B":"meta-llama/llama-guard-4-12b",
            "GPT OSS 120B":"openai/gpt-oss-120b",
            "GPT OSS 20B":"openai/gpt-oss-20b",
            "Whisper":"openai/whisper-large-v3",
            "Whisper Large V3 Turbo":"openai/whisper-large-v3-turbo",
            "Kimi K2 0905":"moonshotai/kimi-k2-instruct-0905",
            "Safety GPT OSS 20B":"openai/gpt-oss-safeguard-20b",
            "Qwen3-32B":"qwen/qwen3-32b"
        }
    },
    {
        "name": "Cerebras",
        "URL_API": "https://cloud.cerebras.ai/platform/org_pv8wc48vp5jd4mctjf2nrdhx/apikeys",
        "URL_models": "https://cloud.cerebras.ai/platform/org_pv8wc48vp5jd4mctjf2nrdhx/models",
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "_top":"gpt-oss-120b",
            "_low":"llama3.1-8b",
            "Llama 3.3 70B": "llama-3.3-70b",
            "llama3.1-8b": "llama3.1-8b",
            "GPT OSS 120B": "gpt-oss-120b",
            "qwen-3-235b-a22b-instruct-2507": "qwen-3-235b-a22b-instruct-2507",
            "qwen-3-32b": "qwen-3-32b",
            "zai-glm-4.6": "zai-glm-4.6",
            "zai-glm-4.7": "zai-glm-4.7"
        }
    },
    {
        "name": "Gemini",
        "URL_API": "https://aistudio.google.com/app/api-keys",
        "URL_models": "https://ai.google.dev/gemini-api/docs/interactions?hl=es-419&ua=chat#supported-models-agents",
        "url": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "_top":"gemini-2.5-flash",
            "_low":"gemini-2.5-flash-lite",
            "gemini-2.5-flash":"gemini-2.5-flash",
            "gemini-2.5-flash-lite":"gemini-2.5-flash-lite",
            "gemini-robotics-er-1.5-preview":"gemini-robotics-er-1.5-preview"
        }
    },
    {
        "name": "openRouter",
        "URL_API": "https://openrouter.ai/settings/keys",
        "URL_models": "https://openrouter.ai/models",
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "_top": "openai/gpt-oss-120b:free",
            "_low": "openai/gpt-oss-20b:free",
            "molmo-2-8b": "allenai/molmo-2-8b:free",
            "mimo-v2-flash:free":"xiaomi/mimo-v2-flash:free",
            "nemotron-3-nano-30b-a3b:free":"nvidia/nemotron-3-nano-30b-a3b:free",
            "devstral-2512":"mistralai/devstral-2512:free",
            "tng-r1t-chimera":"tngtech/tng-r1t-chimera:free",
            "nemotron-nano-12b-v2-vl":"nvidia/nemotron-nano-12b-v2-vl:free",
            "gpt-oss-120b":"openai/gpt-oss-120b:free",
            "gpt-oss-20b":"openai/gpt-oss-20b:free",
            "glm-4.5-air":"z-ai/glm-4.5-air:free",
            "qwen3-coder":"qwen/qwen3-coder:free",
            "kimi-k2":"moonshotai/kimi-k2:free",
            "dolphin-mistral-24b-venice-edition":"cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
            "gemma-3n-e2b-it":"google/gemma-3n-e2b-it:free",
            "deepseek-r1t2-chimera":"tngtech/deepseek-r1t2-chimera:free",
            "deepseek-r1-0528":"deepseek/deepseek-r1-0528:free",
            "gemma-3n-e4b-it":"google/gemma-3n-e4b-it:free",
            "qwen3-4b":"qwen/qwen3-4b:free",
            "gemma-3-27b-it":"google/gemma-3-27b-it:free",
            "gemma-3-4b-it":"google/gemma-3-4b-it:free",
            "gemini-2.0-flash-exp":"google/gemini-2.0-flash-exp:free",
            "Llama 3.3 70B":"meta-llama/llama-3.3-70b-instruct:free",
            "Llama 3.1 8B": "meta-llama/llama-3.1-405b-instruct:free",
            "qwen-2.5-vl-7b-instruct":"qwen/qwen-2.5-vl-7b-instruct:free"
        }
    }




]

def create_example_file():
    """Crea providers.example.json si no existe (para versionar en GitHub)"""
    if not os.path.exists(EXAMPLE_PATH):
        with open(EXAMPLE_PATH, 'w', encoding='utf-8') as f:
            json.dump(DEFAULT_PROVIDERS_CONTENT, f, indent=2, ensure_ascii=False)
        print("✅ providers.example.json creado automáticamente.")

def create_providers_file():
    """Crea providers.json con el ejemplo si no existe (para uso real)"""
    if not os.path.exists(PROVIDERS_PATH):
        with open(PROVIDERS_PATH, 'w', encoding='utf-8') as f:
            json.dump(DEFAULT_PROVIDERS_CONTENT, f, indent=2, ensure_ascii=False)
        print("✅ providers.json creado automáticamente.")
        print("⚠️  RECUERDA: Edita providers.json con tus claves reales de API.")
        print("   No subas este archivo a GitHub (está en .gitignore).")

def get_providers():
    # Primero: aseguramos que el ejemplo exista (para el repo)
    create_example_file()

    # Segundo: si no hay providers.json, lo creamos con el ejemplo
    create_providers_file()

    # Ahora cargamos el real
    try:
        with open(PROVIDERS_PATH, 'r', encoding='utf-8') as f:
            providers = json.load(f)
    except json.JSONDecodeError as e:
        raise ImproperlyConfigured(f"Error de sintaxis JSON en providers.json: {e}")

    # Validación
    if not isinstance(providers, list) or len(providers) == 0:
        raise ImproperlyConfigured("providers.json debe contener al menos un proveedor.")

    for i, provider in enumerate(providers):
        required = ['name', 'url', 'api_key']
        missing = [k for k in required if k not in provider]
        if missing:
            raise ImproperlyConfigured(f"Proveedor #{i+1} ({provider.get('name', 'desconocido')}) falta campos: {missing}")

        if 'model_map' in provider and not isinstance(provider['model_map'], dict):
            raise ImproperlyConfigured(f"model_map en {provider['name']} debe ser un objeto.")

    return providers

# Cargamos los proveedores (esto ejecuta la lógica de creación automática)
AI_PROVIDERS = get_providers()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment or .env using python-decouple

# --- Creación automática del .env (si no existe) ---
def create_env_file():
    """
    Crea .env si no existe (para uso real).
    - Genera SECRET_KEY segura si falta.
    - Añade PROXY_API_KEY=None por defecto.
    - No sobrescribe si ya existe.
    """
    if not os.path.exists(ENV_PATH):
        secret = secrets.token_urlsafe(50)  # ~ 67 chars base64-url
        lines = [
            f"SECRET_KEY={secret}\n",
            "PROXY_API_KEY=None\n",
        ]
        with open(ENV_PATH, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        print("✅ .env creado automáticamente.")
        print("⚠️ RECUERDA: Si vas a desplegar en producción, rota y guarda la SECRET_KEY de forma segura.")
    else:
        # Si existe, asegurar claves mínimas sin sobrescribir
        with open(ENV_PATH, 'r', encoding='utf-8') as f:
            content = f.read()

        updated = False
        if "SECRET_KEY=" not in content:
            with open(ENV_PATH, 'a', encoding='utf-8') as f:
                f.write(f"SECRET_KEY={secrets.token_urlsafe(50)}\n")
            updated = True

        if "PROXY_API_KEY=" not in content:
            with open(ENV_PATH, 'a', encoding='utf-8') as f:
                f.write("PROXY_API_KEY=None\n")
            updated = True

        if updated:
            print("🔧 .env actualizado con claves faltantes.")
        else:
            print("ℹ️ .env ya contiene las claves necesarias.")


# --- Carga segura y validación de variables ---
def get_env_settings():
    """
    Garantiza que .env exista, carga y valida SECRET_KEY y PROXY_API_KEY.
    Devuelve (SECRET_KEY, PROXY_API_KEY).
    """
    # Primero: aseguramos que el .env exista (para el proyecto)
    create_env_file()

    # Cargamos con python-decouple usando RepositoryEnv directo al archivo .env
    # (Alternativa a decouple.config, para poder manejar mejor errores/localización)
    if not os.path.exists(ENV_PATH):
        raise ImproperlyConfigured(f"No se encontró el archivo .env en: {ENV_PATH}")

    config = Config(RepositoryEnv(ENV_PATH))

    # SECRET_KEY: obligatoria y no vacía
    try:
        secret_key = config('SECRET_KEY')
    except Exception as e:
        raise ImproperlyConfigured(f"SECRET_KEY no definida en .env: {e}")

    if not secret_key or isinstance(secret_key, str) and secret_key.strip() == "":
        raise ImproperlyConfigured("SECRET_KEY está vacía en .env.")

    # PROXY_API_KEY: opcional, 'None' se interpreta como None real
    proxy_api_key_raw = config('PROXY_API_KEY', default='None')
    proxy_api_key = None if str(proxy_api_key_raw).strip().lower() in ('', 'none', 'null') else proxy_api_key_raw

    return secret_key, proxy_api_key


# --- Uso en settings.py ---
SECRET_KEY_, PROXY_API_KEY_ = get_env_settings()
SECRET_KEY = SECRET_KEY_
PROXY_API_KEY =  PROXY_API_KEY_


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "http://localhost:3000",
    "https://tu-dominio.com",
    "*",
]
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # Tu frontend React/Vanilla/whatever
#     "https://tu-dominio.com",
#     "*",
# ]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'django_openapi_proxy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_openapi_proxy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
