"""
Django settings for django_openapi_proxy project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROVIDERS_PATH = os.path.join(BASE_DIR, 'providers.json')
EXAMPLE_PATH = os.path.join(BASE_DIR, 'providers.example.json')

# Contenido del ejemplo (con claves falsas y comentarios explicativos)
DEFAULT_PROVIDERS_CONTENT = [
    {
        "name": "Grok (xAI)",
        "url": "https://api.x.ai/v1/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "gpt-4o-mini": "grok-beta",
            "gpt-4o": "grok-beta",
            "gpt-4": "grok-pro"
        }
    },
    {
        "name": "Cerebras",
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "model_map": {
            "gpt-4o-mini": "llama3.1-70b",
            "gpt-4o": "llama3.1-70b",
            "gpt-3.5-turbo": "llama3.1-8b"
        }
    }
]

def create_example_file():
    """Crea providers.example.json si no existe (para versionar en GitHub)"""
    if not os.path.exists(EXAMPLE_PATH):
        with open(EXAMPLE_PATH, 'w', encoding='utf-8') as f:
            json.dump(DEFAULT_PROVIDERS_CONTENT, f, indent=2, ensure_ascii=False)
        print("✅ providers.example.json creado automáticamente.")

def create_providers_file():
    """Crea providers.json con el ejemplo si no existe (para uso real)"""
    if not os.path.exists(PROVIDERS_PATH):
        with open(PROVIDERS_PATH, 'w', encoding='utf-8') as f:
            json.dump(DEFAULT_PROVIDERS_CONTENT, f, indent=2, ensure_ascii=False)
        print("✅ providers.json creado automáticamente.")
        print("⚠️  RECUERDA: Edita providers.json con tus claves reales de API.")
        print("   No subas este archivo a GitHub (está en .gitignore).")

def get_providers():
    # Primero: aseguramos que el ejemplo exista (para el repo)
    create_example_file()

    # Segundo: si no hay providers.json, lo creamos con el ejemplo
    create_providers_file()

    # Ahora cargamos el real
    try:
        with open(PROVIDERS_PATH, 'r', encoding='utf-8') as f:
            providers = json.load(f)
    except json.JSONDecodeError as e:
        raise ImproperlyConfigured(f"Error de sintaxis JSON en providers.json: {e}")

    # Validación
    if not isinstance(providers, list) or len(providers) == 0:
        raise ImproperlyConfigured("providers.json debe contener al menos un proveedor.")

    for i, provider in enumerate(providers):
        required = ['name', 'url', 'api_key']
        missing = [k for k in required if k not in provider]
        if missing:
            raise ImproperlyConfigured(f"Proveedor #{i+1} ({provider.get('name', 'desconocido')}) falta campos: {missing}")

        if 'model_map' in provider and not isinstance(provider['model_map'], dict):
            raise ImproperlyConfigured(f"model_map en {provider['name']} debe ser un objeto.")

    return providers

# Cargamos los proveedores (esto ejecuta la lógica de creación automática)
AI_PROVIDERS = get_providers()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment or .env using python-decouple
SECRET_KEY = config('SECRET_KEY')
# Opcional: clave para proteger tu proxy
PROXY_API_KEY = config('PROXY_API_KEY', default=None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "http://localhost:3000",
    "https://tu-dominio.com",
    "*",
]
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  # Tu frontend React/Vanilla/whatever
#     "https://tu-dominio.com",
#     "*",
# ]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'django_openapi_proxy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_openapi_proxy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
